SQLALCHEMY_DATABASE_URI = 'mysql://root:Abc!@8851043@127.0.0.1/test'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf-8"
DEBUG = True
SQLALCHEMY_ECHO = True
RELEASW_VERSION =""
UPLOAD_FOLDER = '/path/to/the/uploads'
